version: '3.7'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'restaurant_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'restaurant'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # Forward host port 8306 to guest port 3306 (MySQL default port). This means that applications external to the
      # container cluster can access MySQL within the container on port 8306 and the requests are forwarded to port 3306
      # within the cluster.
      - '8306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: